apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: personbruker
  name: innholdsoversikt-dashboard
  namespace: personbruker
spec:
  accessPolicy:
    outbound:
      external:
        - host: nav-enonicxp-dataquery.intern.nav.no
  image: {{ image }}
  schedule: '0 6 1 * *'
  resources:
    requests:
      cpu: 500m
      memory: 2Gi
    limits:
      cpu: 500m
      memory: 2Gi
  webproxy: true
  env:
    - name: GCP_BQ_OPPDATERING_CREDS
      value: /var/run/secrets/secrets.json
  filesFrom:
    - secret: innholdsmengde-dashboard-secrets
  backoffLimit: 0

