[tool.poetry]
name = "innholdsoversikt"
version = "0.1.0"
description = "cronjob for å hente innhold og innholdsmengde fra enonic xp"
authors = ["Team personbruker"]
readme = "README.md"
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.9.0,<3.11"
pandas = "^1.3.5"
xmltodict = "^0.12.0"
tqdm = "^4.62.3"
google-cloud-bigquery = "^2.31.0"
google-cloud-storage = "^1.43.0"
pyarrow = "^6.0.1"

[tool.poetry.dev-dependencies]
ipykernel = "^6.6.0"
black = "^22.1.0"
openpyxl = "^3.0.9"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
