[project]
name = "innholdsoverikt"
version = "0.2.0"
description = "cronjob for å hente innhold og innholdsmengde fra enonic xp"
readme = "README.md"
requires-python = ">=3.10"
license = {file = "LICENSE"}

dependencies = [
    "cachetools==5.3.1",
    "certifi==2023.5.7",
    "charset-normalizer==3.1.0",
    "google-api-core[grpc]==2.11.0",
    "google-auth==2.19.0",
    "google-cloud-bigquery==3.10.0",
    "google-cloud-core==2.3.2",
    "google-cloud-storage==2.9.0",
    "google-crc32c==1.5.0",
    "google-resumable-media==2.5.0",
    "googleapis-common-protos==1.59.0",
    "grpcio==1.54.2",
    "grpcio-status==1.54.2",
    "idna==3.4",
    "numpy==1.24.3",
    "packaging==23.1",
    "pandas==2.0.2",
    "proto-plus==1.22.2",
    "protobuf==4.23.2",
    "pyarrow==12.0.0",
    "pyasn1==0.5.0",
    "pyasn1-modules==0.3.0",
    "python-dateutil==2.8.2",
    "python-dotenv==1.0.0",
    "pytz==2023.3",
    "requests==2.31.0",
    "rsa==4.9",
    "six==1.16.0",
    "tqdm==4.65.0",
    "tzdata==2023.3",
    "urllib3==1.26.16",
    "xmltodict==0.13.0"
]

[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"